config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  #Nesting the review pages into the movie pages
  resources :movies do
    #Allowing users to search
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
  #For contact page and email
  get 'contact', to: 'movies#contact'
  post 'request_contact', to: 'movies#request_contact'
  #Setting the index page as root page
  root'movies#index'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "2018 Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Categories<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <% Category.order('name ASC').each do |category| %>
          <li class="<%= "active" if params[:category] == category.name%>">
            <%= link_to category.name, movies_path(category: category.name), class:"link"%>
          </li>
          <%end%>
         </ul>
        </li>
        <% if user_signed_in? %>
          <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
        <% end %>
      </ul>

       <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
      <form class="navbar-form navbar-right" role: "search">
        <p>
         <%= text_field_tag :search, params[:search], class: "form-control" %>
         <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
       </p>
     <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Review 2018</title>
    <link rel="icon" type="image/jpg" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmUBK9RErGZcm6nM1DMk9EZ8gzSi9b8liKEFwm0yweY4QXMwXgLQ" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>